### create user ###

POST {{host}}/auth/register
Content-Type: application/json

{
    "email": "mattias.guerrero@gmail.com",
    "password": "Abc123",
    "fullName": "Mattias Guerrero"
}

### login ###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "mattias.guerrero@gmail.com",
    "password": "Abc123"
}

### private route test ###

GET {{host}}/auth/private
Authorization: {{token}}

### private2 route test ###

GET {{host}}/auth/private2
Authorization: {{token}}


### private3 route test ###

GET {{host}}/auth/private3
Authorization: {{token}}
